<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://tempuri.org/XMLSchema.xsd"
    elementFormDefault="qualified"
    xmlns="http://tempuri.org/XMLSchema.xsd"
    xmlns:mstns="http://tempuri.org/XMLSchema.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
	<xs:element name="congty">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="phongban" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							
							<xs:element name="tenphong">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Tổ chức"/>
										<xs:enumeration value="Hành chính"/>
										<xs:enumeration value="Đào tạo"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>

							<xs:element name="dienthoai">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="\d{10}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>

							<xs:element name="nhanvien" minOccurs="2" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										
										<xs:element name="manv"/>

										<xs:element name="hoten" type="xs:string"/>

										<xs:element name="trinhdo" type="xs:string" minOccurs="0"/>

										<xs:element name="sonamcongtac" type="xs:integer" minOccurs="0"/>
										
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
